#!/bin/bash

sum=0
i="y"

echo "Please enter a number1."
read n1
echo "Please enter a number2."
read n2
while [ $i = "y" ]
do
echo "1.Add"
echo "2.Subtract"
echo "3.Multiply"
echo "4.Divide"
echo "Enter your choice"
read ch
case $ch in
    1)sum=`expr $n1 + $n2`
     echo "Answer = "$sum;;
        2)sum=`expr $n1 - $n2`
     echo "Answer = "$sum;;
    3)sum=`expr $n1 \* $n2`
     echo "Answer = "$sum;;
    4)sum=`expr $n1 / $n2`
     echo "Answer = "$sum;;
    *)echo "Invalid choice";;
esac
echo "Do u want to continue (y/n) ?"
read i
if [ $i != "y" ]
then
    exit
fi
done
